### ISSUE TITLE
Shadow DOM

### ISSUE THREAD

**Issue by JaapWeijland** [andreadev-it/stacking-contexts-inspector#3]
Hi there,

I'm trying to debug the stacking order of my web component in relation to the hosting page. However, this tool does not seem to detect shadow roots, even if it's set to 'open'. Is this a bug or a missing feature?

**Comment by andreadev-it** [comment]
hi Jaap,
Thank you very much for the info. I initially decided not to focus on shadow dom in order to avoid delaying too much the development, but I think it's correct to start implementing it now. I'll try to add support for the open shadow DOM in the next release. 

Have a nice day!

**Comment by andreadev-it** [comment]
Fixed in 1.1.8
Only open shadow roots are supported.
At the moment the updated extension is already available for firefox, and is undergoing revisions on the chrome web store, so it should be up in a few hours/days.
