### ISSUE TITLE
Add the value of z-index to `Node details` tab

### ISSUE THREAD

**Issue by functor-dev** [andreadev-it/stacking-contexts-inspector#7]
Thank you so much for your very helpful extension.
Currently, I'm using both `CSS Stacking Context inspector` and `z-context` (This one had problem with chrome latest version).

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when checking the z-index of the selected element.
For `z-context`, you can see the z-index directly, no need to switch to the computed tab.

**Describe the solution you'd like**
Show the z-index in `Node details`.

**Additional context**
This is an example of `z-context`

![image](https://user-images.githubusercontent.com/60058060/148314874-54dd351d-7ec2-4adc-a2c3-6d8922f2a756.png)

**Comment by andreadev-it** [comment]
Thank you FunctorDev for the suggestion!
It really seems like something that should have been included from day 1, it will be added for sure in the next version. It will come in the "Node details" or, more probably, the "Context details" section of the sidebar.

**Comment by andreadev-it** [comment]
Fixed in 1.1.11, coming up on both Firefox and Chrome after they're finished with the revision process 🙂

**Comment by functor-dev** [comment]
That's awesome, thank you @andreadev-it 👍
