### ISSUE TITLE
Doesn't seem to report stacking contexts created by `mask-image`

### ISSUE THREAD

**Issue by iansjk** [andreadev-it/stacking-contexts-inspector#8]
Hello! First, thank you for making this extension—it has been very helpful in diagnosing unexpected z-index issues due to stacking contexts.

I wanted to raise an issue regarding `mask-image`, [which according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context#the_stacking_context), creates a stacking context:
> ...
> Element with any of the following properties with value other than none:
> - [transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform)
> - [filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)
> - [backdrop-filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter)
> - [perspective](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective)
> - [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)
> - [mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) / [mask-image](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image) / [mask-border](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border) 

But this extension doesn't seem to report a stacking context created by `mask`. (I haven't tested the others, but it may be the case for the rest of the properties above too.) This confused me for a while because I was trying to diagnose a z-index issue that was ultimately caused by a stacking context created by `mask-image`.

I've created a CodeSandbox that demonstrates the issue I had: https://lqtrkr.csb.app/

If you open up the Stacking Contexts tab, all I see is
```
#document
      div#absolute
```
However, you can see from the visual results that `div#absolute` cannot pierce the stacking context created by `mask-image`, despite an arbitrarily large z-index value, and so the `div.fake-content` with a red background appears atop of it. If you go into the inspector and _remove_ the mask-image property from `div#scroller`, you can see that `div#absolute` now belongs to the initial stacking context and as a result it appears atop the red background.

I hope that helps explain the issue! Please let me know if I'm misunderstanding something about how the extension is supposed to work, or if you need any more detail. Thanks!

**Comment by andreadev-it** [comment]
Hello Ian,
Thank you very much for your report and for the detailed explanation with examples, it was very helpful!
The code was meant to look for these properties too, but I hadn't thought about prefixes. By looking at the example you've shared, it seems that the problem is easily fixable on my part by adding checks for the webkit-prefixed properties.

I'll let you know here when the new version is being published, thank you again for sharing this issue!

**Comment by andreadev-it** [comment]
The update has been uploaded to the Chrome Web Store and Firefox Addons.
Thank you again and have a nice day 🙂

**Comment by iansjk** [comment]
Wow, thanks so much for the quick response and fix!
